services:
  mint:
    build:
      context: .
      args:
        USER: ${USER}
        UID: ${UID}
        GID: ${GID}
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/docs
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - NODE_ENV=development

  npm:
    build:
      context: .
      args:
        USER: ${USER}
        UID: ${UID}
        GID: ${GID}
    volumes:
      - .:/docs
    entrypoint: ["npm"]

